Fixed SonarLint issues
rhalm/ivt-lab pull request #3
Opened 2021-04-30 23:08 UTC by rhalm

2021-04-30 23:10 UTC, rhalm commented
Fixed 3 issues in TorpedoStore.java

2021-05-02 13:10 UTC, AnKa0 requested changes
Írj kommenteket!

2021-05-02 13:10 UTC, AnKa0 commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  private Random generator = new Random();
Használj inkább SecureRandom-ot

2021-05-02 13:10 UTC, AnKa0 commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      throw new IllegalArgumentException("numberOfTorpedos");
Zseniális!

2021-05-02 14:03 UTC, AnKa0 approved these changes

2021-05-02 14:07 UTC, merged